version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:password@host.docker.internal:3306/speer
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      DATABASE_URL: mysql://root:password@host.docker.internal:3306/speer
      MYSQL_DATABASE: speer
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
